import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  email: "",
  status: "",
  mainSubject: "",
  userUUID: "",
};

export const profileSlice = createSlice({
  name: "profile",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    login: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes

      state.email = action.payload.email;
      state.mainSubject = action.payload.mainSubject;
      state.status = "logged-in";
      state.userUUID = action.payload.uid;
    },
    logout: (state) => {
      localStorage.clear("user");
      return {};
    },
    error: (state, action) => {
      console.log(action);
      state.errorMessage = action.payload.errorMessage;
    },

    // Use the PayloadAction type to declare the contents of `action.payload`
    //   incrementByAmount: (state, action) => {
    //     state.value += action.payload;
    //   },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = 'loading';
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle';
  //       state.value += action.payload;
  //     });
  // },
});

export const { login, logout, error } = profileSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectMainSubject = (state) => state.profile.mainSubject;
export const selectEmail = (state) => state.profile.email;
export const selectStatus = (state) => state.profile.status;
export const selectUser = (state) => state.profile.user;
export const selectError = (state) => state.profile.errorMessage;

export default profileSlice.reducer;
